[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.10.5"
#serde_scan = "0.4.1"
serde = { version = "1.0.147", features = ["derive"] }
sscanf = "0.4.0"
nom = "7.1.1"
arrayvec = "0.7.2"